import type { CVData, JobMatch } from "@/types";

export const DEMO_CV: CVData = {
  name: "Atif Chowdhury",
  email: "atif.chy@email.com",
  phone: ["+8801700000000"],
  location: "Dhaka, Bangladesh",
  summary:
    "Software engineer with 3 years of experience in Python, React and machine learning. Passionate about building scalable backend systems and intelligent data pipelines.",
  skills: [
    "Python",
    "React",
    "FastAPI",
    "PostgreSQL",
    "Docker",
    "Machine Learning",
    "TensorFlow",
    "Git",
    "REST API",
    "JavaScript",
    "Linux",
    "Redis",
    "Windows",
  ],
  experience: [
    {
      title: "Software Engineer",
      company: "TechCorp BD",
      startDate: "2022-01",
      endDate: "Present",
      description:
        "Built backend microservices in Python/FastAPI. Led ML pipeline for customer churn prediction.",
    },
    {
      title: "Junior Developer",
      company: "Startup XYZ",
      startDate: "2021-01",
      endDate: "2021-12",
      description: "Developed React dashboard and REST APIs. Worked with PostgreSQL and Docker.",
    },
  ],
  education: [
    {
      degree: "B.Sc. Computer Science & Engineering",
      institution: "BUET",
      year: "2021",
    },
    {
      degree: "Higher Secondary Certificate (HSC)",
      institution: "Dhaka College",
      year: "2019",
    },
  ],
  languages: ["English", "Bengali"],
  certifications: ["AWS Cloud Practitioner"],
  references: [],
};

export const DEMO_MATCHES: JobMatch[] = [
  {
    job_id: "101",
    job_title: "Senior Python Developer",
    company: "DataBridge Ltd",
    location: "Dhaka",
    salary_range: "BDT 80,000 – 120,000",
    deadline: "30 Apr 2026",
    final_score: 87.4,
    breakdown: {
      skill_match: 91,
      education_match: 88,
      experience_match: 75,
      semantic_match: 82,
      title_match: 79,
      skill_source: 85,
      seniority_penalty: 1.0,
    },
  },
  {
    job_id: "102",
    job_title: "Backend Engineer (FastAPI)",
    company: "FinTech Solutions",
    location: "Dhaka",
    salary_range: "BDT 70,000 – 100,000",
    deadline: "15 May 2026",
    final_score: 83.1,
    breakdown: {
      skill_match: 88,
      education_match: 85,
      experience_match: 70,
      semantic_match: 78,
      title_match: 72,
      skill_source: 80,
      seniority_penalty: 1.0,
    },
  },
  {
    job_id: "103",
    job_title: "ML Engineer",
    company: "AI Ventures BD",
    location: "Dhaka",
    salary_range: "BDT 90,000 – 130,000",
    deadline: "20 Apr 2026",
    final_score: 79.6,
    breakdown: {
      skill_match: 82,
      education_match: 90,
      experience_match: 65,
      semantic_match: 74,
      title_match: 68,
      skill_source: 78,
      seniority_penalty: 0.9,
    },
  },
  {
    job_id: "104",
    job_title: "Full Stack Developer",
    company: "DevHouse",
    location: "Dhaka (Remote)",
    salary_range: "BDT 60,000 – 90,000",
    deadline: "10 May 2026",
    final_score: 74.2,
    breakdown: {
      skill_match: 76,
      education_match: 80,
      experience_match: 70,
      semantic_match: 68,
      title_match: 65,
      skill_source: 72,
      seniority_penalty: 1.0,
    },
  },
  {
    job_id: "105",
    job_title: "Data Engineer",
    company: "Analytics Corp",
    location: "Dhaka",
    salary_range: "BDT 75,000 – 110,000",
    deadline: "25 Apr 2026",
    final_score: 71.8,
    breakdown: {
      skill_match: 74,
      education_match: 88,
      experience_match: 60,
      semantic_match: 70,
      title_match: 62,
      skill_source: 68,
      seniority_penalty: 1.0,
    },
  },
  {
    job_id: "106",
    job_title: "DevOps Engineer",
    company: "CloudBD",
    location: "Dhaka",
    salary_range: "BDT 85,000 – 115,000",
    deadline: "5 May 2026",
    final_score: 65.3,
    breakdown: {
      skill_match: 68,
      education_match: 78,
      experience_match: 55,
      semantic_match: 60,
      title_match: 58,
      skill_source: 62,
      seniority_penalty: 0.95,
    },
  },
  {
    job_id: "107",
    job_title: "React Developer",
    company: "UX Studio",
    location: "Dhaka",
    salary_range: "BDT 55,000 – 80,000",
    deadline: "12 May 2026",
    final_score: 61.5,
    breakdown: {
      skill_match: 64,
      education_match: 72,
      experience_match: 60,
      semantic_match: 56,
      title_match: 52,
      skill_source: 58,
      seniority_penalty: 1.0,
    },
  },
];
